package Application.Controllers;

import Application.Model.Usuario;
import Application.Repositories.UsuarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/Usuarios") // This means URL's start with /Usuarios (after Application path)
public class UsuariosController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsuarioRepository userRepository;

    @GetMapping(path="/")
    public Iterable<Usuario> getUsuarios() {
        return userRepository.findAll();
    }

    @PostMapping(path = "/add")
    public String addUsuario(@RequestParam String username) {
        Usuario u = new Usuario(username);
        userRepository.save(u);
        return "Saved";
    }

    @DeleteMapping(path = "/delete")
    public String deleteUsuario(@RequestParam long id) {
        userRepository.deleteById(id);
        return "Deleted";
    }
}
